name: Pipeline

on:
  push:
    branches:
     - master
  pull_request:
    - master

jobs:
  pipeline:
    runs-on: ubuntu-latest  # This is equivalent to 'agent any' in Jenkins
    
    steps:
      # Stage One
      - name: Stage One
        run: |
          echo 'step 1'
          sleep 3

      # Stage Two
      - name: Stage Two
        run: |
          echo 'step 2'
          sleep 9

      # Stage Three
      - name: Stage Three
        run: |
          echo 'step 3'
          sleep 5

      # Post Actions (always run)
      - name: Post Actions
        if: always()  # This ensures the step runs even if previous steps fail
        run: echo 'This pipeline is completed.'
